version: '3.0'

services:
  grafana:
    container_name: 'jdbranham-diagram-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-10.2.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/jdbranham-diagram-panel
      - ./provisioning:/etc/grafana/provisioning
